# Input and Output paths
input_file: "/Users/ishaharris/Projects/TCR/clono-scan/data/highconf/AC02.tsv"
output_file: "/Users/ishaharris/Projects/TCR/clono-scan/data/decoys/AC02_decoy.csv"

# Model Settings
species: "human"  # 'human' or 'mouse'

parameters:
  # Levenshtein Distance (L)
  # Decoys must be strictly > L distance away from ANY validated sequence
  # If L=1, distance must be 2 or more.
  levenshtein_distance_threshold: 3

  # Number of decoys to generate per input sequence
  decoys_per_sequence: 1

  # Pgen Matching Tolerance (Log10 units)
  # 1.0 means the decoy Pgen must be within 1 order of magnitude of the target
  # 0.5 is stricter, 2.0 is looser
  pgen_tolerance_log10: 2.0

  # Performance Tuning
  # How many random candidates to attempt to generate for each V-J-Length bucket
  # Increase this if you find '0 decoys found' for many rows.
  pool_prime_min_candidates: 100