# --- File Paths ---
# Path to your input TSV/CSV containing 'junction_aa', 'v_call', and 'j_call'
input_file: "/Users/ishaharris/Projects/TCR/clono-scan/data/highconf/AC02.tsv"

# Where to save the results
output_file: "/Users/ishaharris/Projects/TCR/clono-scan/data/decoys/scrambled/AC02_scrambled.csv"

# --- Biological Settings ---
# Options: 'human' or 'mouse' (default is human)
species: "human" 

# --- Algorithm Parameters ---
parameters:
  decoys_per_sequence: 1
  pgen_tolerance_log10: 1  # You can probably keep this tight now (0.5 or 0.3)
  levenshtein_distance_threshold: 4
  max_scramble_iterations: 3000
  anchor_length: 2
  
  # NEW PARAMETER
  # Defines the max number of amino acids to swap in one attempt. 
  # The script will randomly choose between 1 and this number.
  max_mutations_per_attempt: 8